version: 2

sources:
  - name: postgres
    schema: oltp
    tables:
      - name: category_products
        description: "TBD"
        columns:
          - name: "categoryid"
            description: "TBD"
          - name: "categoryname"
            description: "TBD"
          - name: "description"
            description: "TBD"

      - name: product_review
        description: "TBD"
        columns:
          - name: "reviewid"
            description: "TBD"
          - name: "itemid"
            description: "TBD"
          - name: "score"
            description: "TBD"
          - name: "reviewcomment"
            description: "TBD"
      
      - name: customers
        description: "TBD"
        columns:
          - name: "customerid"
            description: "TBD"
          - name: "cpf"
            description: "TBD"
          - name: "firstname"
            description: "TBD"
          - name: "lastname"
            description: "TBD"
          - name: "gender"
            description: "TBD"
          - name: "birth"
            description: "TBD"
          - name: "emailaddress"
            description: "TBD"
          - name: "phone"
            description: "TBD"
          - name: "created"
            description: "TBD"
      - name: addresses
        description: "TBD"
        columns:
          - name: "addressid"
            description: "TBD"
          - name: "customerid"
            description: "TBD"
          - name: "street"
            description: "TBD"
          - name: "streetnumber"
            description: "TBD"
          - name: "neighborhood"
            description: "TBD"
          - name: "city"
            description: "TBD"
          - name: "state"
            description: "TBD"
          - name: "code"
            description: "TBD"
      - name: order_items
        description: "TBD"
        columns:
          - name: "itemid"
            description: "TBD"
          - name: "orderid"
            description: "TBD"
          - name: "productid"
            description: "TBD"
          - name: "quantity"
      - name: orders
        description: "TBD"
        columns:
          - name: "orderid"
            description: "TBD"
          - name: "customerid"
            description: "TBD"
          - name: "addressid"
            description: "TBD"
          - name: "payment"
            description: "TBD"
          - name: "installments"
            description: "TBD"
          - name: "date"
            description: "TBD"
      - name: product_price
        description: "TBD"
        columns:
          - name: "priceid"
            description: "TBD"
          - name: "productid"
            description: "TBD"
          - name: "startdate"
            description: "TBD"
          - name: "enddate"
            description: "TBD"
          - name: "price"
      - name: products
        description: "TBD"
        columns:
          - name: "productid"
            description: "TBD"
          - name: "categoryid"
            description: "TBD"
          - name: "productname"
            description: "TBD"
          - name: "description"
            description: "TBD"