version: 2

sources:
  - name: postgres
    schema: staging
    tables:
      - name: stg_addresses
        description: "TBD"
        columns:
        - name: "id_address"
          description: "TBD"
        - name: "id_customer"
          description: "TBD"
        - name: "street"
          description: "TBD"
        - name: "num_street"
          description: "TBD"
        - name: "neighborhood"
          description: "TBD"
        - name: "city"
          description: "TBD"
        - name: "zip_code"
          description: "TBD"
      - name: stg_customers
        description: "TBD"
        columns:
          - name: "id_customer"
            description: "TBD"
          - name: "cpf_customer"
            description: "TBD"
          - name: "first_name"
            description: "TBD"
          - name: "last_name"
            description: "TBD"
          - name: "full_name"
            description: "TBD"
          - name: "date_birth"
            description: "TBD"
          - name: "gender"
            description: "TBD"
          - name: "email_address"
            description: "TBD"
          - name: "phone_number"
            description: "TBD"
          - name: "created_at"
            description: "TBD"
      - name: stg_products
        description: "TBD"
        columns:
        - name: "id_product"
          description: "TBD"
        - name: "name_product"
          description: "TBD"
        - name: "name_category"
          description: "TBD"
        - name: "description_product"
          description: "TBD"
        - name: "description_category"
          description: "TBD"
      - name: stg_order_items
        description: "TBD"
        columns:
        - name: "id_item"
          description: "TBD"
        - name: "id_order"
          description: "TBD"
        - name: "id_product"
          description: "TBD"
        - name: "item_quantity"
          description: "TBD"
        - name: "unit_price"
          description: "TBD"
        - name: "itens_price"
          description: "TBD"
        - name: "score"
          description: "TBD"
      - name: stg_orders
        description: "TBD"
        columns:
        - name: "id_order"
          description: "TBD"
        - name: "id_customer"
          description: "TBD"
        - name: "id_address"
          description: "TBD"
        - name: "payment_method"
          description: "TBD"
        - name: "num_installments"
          description: "TBD"
        - name: "date_order"
          description: "TBD"
      - name: stg_category_products
        description: "TBD"
        columns:
        - name: "id_category"
          description: "TBD"
        - name: "name_category"
          description: "TBD"
        - name: "category_description"
          description: "TBD"
      - name: stg_product_price
        description: "TBD"
        columns:
        - name: "id_price"
          description: "TBD"
        - name: "id_product"
          description: "TBD"
        - name: "date_start"
          description: "TBD"
        - name: "date_end"
          description: "TBD"
        - name: "unit_price"
          description: "TBD"
      - name: stg_product_review
        description: "TBD"
        columns:
        - name: "id_review"
          description: "TBD"
        - name: "id_item"
          description: "TBD"
        - name: "score"
          description: "TBD"
        - name: "comment_review"
          description: "TBD"
